### PR TITLE
CRAN Release 0.3.5

### PR DESCRIPTION
**Pull request by ijlyttle**
Hi @nathancday - I thought I would "live-blog" what I'm doing here. It's just a series of manual checks based of:

- this checklist: #87
- what Hadley says here: https://r-pkgs.org/release.html

I'll try to fill in the blanks in the comments.

### CODE REVIEW

**Comment by ijlyttle** [comment]
Kicked off:

```
devtools::check_win_devel()
```

To check on the CRAN Windows service that checks on R-devel version - results in a wee while.

**Comment by nathancday** [comment]
*just tuned in to the live stream*

Looking good!

**Comment by ijlyttle** [comment]
First feedback - minor setback. Email from win-devel service:

```
Dear package maintainer,

this notification has been generated automatically.
Your package boxr_0.3.5.tar.gz has been built (if working) and checked for Windows.
Please check the log files and (if working) the binary package at: https://win-builder.r-project.org/3IwWWFu6tXaO/
The files will be removed after roughly 72 hours.
Installation time in seconds: 12
Check time in seconds: 106
Status: 1 NOTE
R Under development (unstable) (2019-11-12 r77405)

All the best,
Uwe Ligges
(CRAN maintainer of binary packages for Windows)
```

This leads to https://win-builder.r-project.org/3IwWWFu6tXaO/00check.log, which states:

```
* checking CRAN incoming feasibility ... NOTE
Maintainer: 'Ian Lyttle <ian.lyttle@schneider-electric.com>'

New maintainer:
  Ian Lyttle <ian.lyttle@schneider-electric.com>
Old maintainer(s):
  Brendan Rocks <foss@brendanrocks.com>

Found the following (possibly) invalid file URIs:
  URI: README.md
    From: NEWS.md
  URI: R/README.md
    From: NEWS.md
```

The new-maintainer note is to be expected - gotta fix something in the NEWS...

**Comment by ijlyttle** [comment]
Fixed (🤞), rinse-and-repeat with `check_win_devel()`.

**Comment by ijlyttle** [comment]
We got a clean check this time 🎉: https://win-builder.r-project.org/9GR231rqGSnX/00check.log

Next - r-hub checks

**Comment by nathancday** [comment]
Yeaaaa buddy!

**Comment by ijlyttle** [comment]
Following: https://gargle.r-lib.org/articles/articles/managing-tokens-securely.html

They suggest:

```r
rhub::check(env_vars = Sys.getenv(gargle:::secret_pw_name("gargle"), names = TRUE))
```

for us, this becomes:

```r
rhub::check(env_vars = Sys.getenv(gargle:::secret_pw_name("boxr"), names = TRUE))
```

I might do this first, before the CRAN checks, to run the API tests - maybe it will be separate from the CRAN checks.

**Comment by nathancday** [comment]
Maybe we don't even test on rhub? We have working tests on Travis for peace of mind, and even there sometime we have to restart a build to get it to work

**Comment by nathancday** [comment]
i.e. Just pass the empty "" in?

**Comment by ijlyttle** [comment]
Getting what I think is an unrelated error at rhub: https://builder.r-hub.io/status/boxr_0.3.5.tar.gz-fb2edf8f6c8d489a9dc9e06a936b4fa9

It seems not to be able to load a package. 

I agree that this is a bit unrelated, but I wanted to test out the auth system, as advertised.

I think I might move straight for the CRAN checks at r-hub, not using auth:

```r
rhub::check_for_cran()
```

**Comment by nathancday** [comment]
100% unrelated, we don't have any Bioconducter dependencies, I'm guessing the Rhub image just pulls all possible installer packages first, `BiocManager` being one of them.

Not sure this won't crop up later on the psuedo-CRAN check too...

**Comment by ijlyttle** [comment]
Agreed - sometimes r-hub gets a bit "out-of-sorts", but it has given me useful feedback.

One of the submissions has come back OK - I'll wait a little while for the others.

**Comment by nathancday** [comment]
I'm guessing they will all be okay, the Windows build is the most different from the Travis env.

I have to log off the stream, but if anything comes up let me know and I'll be back later this afternoon. 🤞

**Comment by ijlyttle** [comment]
rhub checks come back OK

**Comment by ijlyttle** [comment]
My plan is:
- [ ] spell-check the function-documentation
- [ ] run remote (win-devel, rhub) checks again
- [ ] submit

**Comment by ijlyttle** [comment]
An just reminded of `devtools::spell_check()`, which would have been useful to remember earlier...

**Comment by ijlyttle** [comment]
🚀

**Comment by ijlyttle** [comment]
On CRAN 🎉

**Comment by nathancday** [comment]
Stickers inbound! I'm putting one on my machine tonight! Damn it feels good!

**Comment by ijlyttle** [comment]
Indeed! Thanks for everything you've done!

**Pull request merged**
