### PR TITLE
Gh actions

### PR DESCRIPTION
**Pull request by ijlyttle**
start on #162

### CODE REVIEW

**Comment by ijlyttle** [comment]
@nathancday - my thought is to do this in stages, but the PR has to be accepted in order to get the ball rolling.

I'm thinking something like this:

- get GH Actions working for R CMD CHECK without API testing
- disable Travis, Appveyor
- get GH Actions working by adding API testing (remove it from Travis, so we can avoid conflicts)
- get GH Actions working for automatic pkgdown builds

Given that this is iterative, would you be ok with me accepting my own PRs on this for a while? Of course, I'd be happy to work together interactively, say, over the weekend, if you'd like. My biggest worry is getting the secret set-up again for the Box account.

**Comment by nathancday** [comment]
That sounds like a good plan, I know you've wanted to migrate for a while. I'd prefer to get the functions we want from the pre-existing PRs (collab/saveRDS/version) merged before we change our CI. Does that sound reasonable?

**Comment by ijlyttle** [comment]
Sounds reasonable, let's do it!

**Comment by nathancday** [comment]
Just doubling back on this my thinking matches yours...This is happens post 3.6 release right?

**Comment by ijlyttle** [comment]
yes!

**Comment by ijlyttle** [comment]
closing in favor of #205

**Pull request closed without merging**
