### PR TITLE
use httr::RETRY to wrap POST

### PR DESCRIPTION
**Pull request by nathancday**
Use httr's version of `purrr::insistently()` in `box_auth_service()`.

I don't think this would make sense to add in `box_auth()`, thoughts?

### CODE REVIEW

**Comment by ijlyttle** [comment]
Nice!

I think the operative function in `box_auth()` is `httr::oauth2.0_token()` - this does not seem amenable to `httr::RETRY()`, so perhaps `purrr::insistently()` might work here?

I think `httr::RETRY()` could be useful also in the internal function `test_request()`.

**Comment by nathancday** [comment]
Ran into an error when wrapping `httr::oauth2.0_token()` with `purrr::insistently()`:

```
Error: Can't convert a `Token2.0/Token/R6` object to function
```

After hitting this snag, I looked into how the new `googlesheets4` is going at interactive OAuth. They are using `gargle::fetch_token()`, which attempts a preset list of credentialing functions, but doesn't retry a failed ones, just moves onto the next, then fails gracefully if all are attempted without success.

Seeing these two pieces, I think we should skip the persistent behavior for `box_auth()`. Interactive users can easily retry if they hit a snag. Plus anyone that wants programmatic/automatic interactions should probably be using the `box_auth_service()` anyway.

**Comment by nathancday** [comment]
@ijlyttle what do you think about abandoning the persistent bit for interactive auth? My feeling is the `HTTR::RETRY()` in service auth will give us what we want and fix #131

**Comment by ijlyttle** [comment]
I think I got this to work - I did a high-tech test where I turned off my wi-fi, then `box_auth()`, then turned it back on again.

Does this work for you?

**Comment by nathancday** [comment]
Looks good to me! Not sure what I was missing, maybe it was me using the `~` syntax instead of the stand-alone function. I can confirm the high-tech test works, green-light to merge?

**Comment by ijlyttle** [comment]
Green light!

**Pull request merged**
