### PR TITLE
Rework box-auth functions 

### LINKED ISSUE #96: functions that write to the filesystem
These need to be looked at with suspicion and scrutiny:

- `box_auth_on_attach()` writes to the `.Renviron` file (and is perhaps more trouble than it's worth)
- `box_auth()` writes a file to the working directory (necessarily so)

### PR DESCRIPTION
**Pull request by ijlyttle**
This will fix #96

- deprecate `box_attach_on_auth()`
- deprecate `write.Renv` arg to `box_auth()`
  - write environment variables to console instead
- refactor `box_auth()`, `box_fresh_auth()`:
  - import glue and fs (both low depencency)

Also, fix typo in `box_read()` documentation

### CODE REVIEW

**Comment by ijlyttle** [comment]
Hi @nathancday -

I don't know how much of an issue this may cause your JWT PR - please let me know if you think there will be an interference.

As well, in the context of #96, I have proposed bigger changes rather than smaller changes. From the users' perpsective the biggest change will be that they will have to update their `.Renviron` file themselves.

**Comment by nathancday** [comment]
Looks good! I can mirror the new .Renviron behavior in `box_auth_jwt()` and don't foresee any issues. I think the bigger changes are good for getting boxr behavior to sync with usethis standards.

Two small questions:
- I think `is_void()` will be useful in `box_auth_jwt()` and maybe else where. Should it be moved to boxr__internal_misc.R? 
- Before I've used `readline("something")` and I see here you are using `message("something") / readline()`. Is there was a reason to prefer one over the other?

**Comment by ijlyttle** [comment]
I'll be happy to move `is_void()` to `boxr__internal_misc.R`.

As for the `readline()` vs. `message()`/`readline()`, I (think) I was just using the existing code as a template. Looking at the documentation the prompt for readline cuts off at 256 characters.

I can adapt my code to use only `readline()` - in the longer run, I understand usethis will be spinning off the `ui_*()` functions to its own package, which I think could be useful to us.

Thanks!

**Comment by nathancday** [comment]
I don't think it's worth changing things to readline() only, that was more
for my knowledge going forward. I'll use that pattern too for consistency.

The PR looks good to merge, after is_void() gets its new home

**Comment by ijlyttle** [comment]
Just to note, the `message()`/`readline()` pattern is used for multiline prompts, so leaving it as it was...

**Pull request merged**
