### PR TITLE
fix box_delete_folder()

### LINKED ISSUE #197: error in box_delete_folder()
```r
box_delete_folder(129842955323)
```

```
folder id 129842955323 sucessfully moved to trash.                                                                                         
box.com remote folder reference

Error: $ operator is invalid for atomic vectors
Backtrace:
    █
 1. ├─[ (function (x, ...) ... ]
 2. └─boxr:::print.boxr_folder_reference(x)
 3.   └─base::cat(" name        :", x$name, "\n")
```

Hopefully this won't take too long to sort out.

### PR DESCRIPTION
**Pull request by ijlyttle**
fix #197

The file and folder API calls return empty content, by Box' design.

In `box_delete_folder()`, we were trying to parse the empty content - leading to the error.

Fixed this, along with a stray documentation fix.

I found that using `r string_side_effects()` was not working within a `{}` structure, so I pasted it in manually.

### CODE REVIEW

**Review by nathancday — APPROVED** [review]
Awesome bug/confusion fix _and_ more test coverage?!? Love it.

**Comment by nathancday** [comment]
Did we double fix the conflicts? Sorry should have communicated better...but looks like this will build green and then we can Squash and Merge

**Comment by ijlyttle** [comment]
there's no problem at all - this is what I had intended to - to pull the other changes into this PR, make sure it all plays nicely together before merging.

sometimes the version numbers collide, that's all this is

**Comment by nathancday** [comment]
Got it okay, I saw the other was .13 and this was .14 so I was gonna merge in that order. Just didn't want to be making more work for you

**Comment by ijlyttle** [comment]
We're on our way!

**Pull request merged**
