### PR TITLE
[WIP] Update documentation 

### PR DESCRIPTION
**Pull request by ijlyttle**
My goal (perhaps this weekend) is to polish the documentation in support of a CRAN release. The results of this PR can be seen at: https://ijlyttle.github.io/boxr/

When the PR is accepted, the main site will be updated.

My purpose in making this PR is to give @nathancday a chance to look things over (thanks Nate!)

Here's what I plan to for this PR:

- [x] create a function-reference page in pkgdown, grouping the functions
- [x] have a single, local source for images (screenshots) - this is `man/figures`
- [x] harmonize the titles of the function help-pages
- [ ] harmonize the content of the function help-pages
- [ ] amend the content of README and boxr article 
- [ ] make sure we have references to the new organization URL

### CODE REVIEW

**Comment by ijlyttle** [comment]
At this point, I have summarized in the README in favor of putting details in the "Get Started" article.

As a result, the article is currently in an unfinished state, so that I could but links from README to an amended framework in the article.

**Comment by nathancday** [comment]
I think you did an excellent job on rewording the documentation, much cleaner. One small change request would be to bump the copy write year in README.md up to 2019. I think the README is good for getting started, because that's what people will land on first. Overall LGTM 😄

**Comment by ijlyttle** [comment]
Thanks Nate! Because I am lazy, I have put the year on cruise-control 🤓

https://github.com/ijlyttle/boxr/blob/73908e67a619d40bacc1fa2dccad465e195ad890/README.Rmd#L98

I very much appreciate you looking this over; I'll ping you when I will have "finished" wrestling with the "Get started" article.

**Comment by nathancday** [comment]
It's the least I can do, you've been cranking on the pkgdwn site part and I've just been watching 😊  The site looks great, let me know if there are other issues I can help with. Right now I am the one on cruise control

**Comment by ijlyttle** [comment]
I think, for now, I want to get a handle on what this package *actually* does, as opposed to what I *think* it does - for me, the best way is just to wrestle with the documentation.

I am starting to build a bit of a roadmap in my head; not to worry, there will be lots for us to do!

**Comment by ijlyttle** [comment]
short-circuiting this PR for now to make sure that the automatic gh-pages deployment works - will re-open and resume

**Pull request merged**
